name: backend
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies_core:
    path: ../dependencies_core
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
